#!/usr/bin/env python3
"""
A script that submits a job to the queue
"""


import sys
from configparser import ConfigParser
from yascheduler.yascheduler import Yascheduler

setup_input = open(sys.argv[1]).read()
struct_input = open(sys.argv[2]).read()
label = setup_input.splitlines()[0]

config = ConfigParser()
config.read('env.ini')
yac = Yascheduler(config)
task_id = yac.queue_submit_task(label, dict(structure=struct_input, input=setup_input))
print("Successfully submitted task: {}".format(task_id))
